### ISSUE TITLE
[BUG] Won't open on Ubuntu 24.10 (Error 71 (Protocol error) dispatching to Wayland display.)

### ISSUE THREAD

**Issue by Deewens** [largestgithubuseronearth/addwater#37]
**Describe the bug**
On a fresh Ubuntu install, I installed flatpak and downloaded Add Water. When I open the app, nothing happens. So I tried to run it from the terminal and got some logs as well as an error :
> Gdk-Message: 20:01:35.592: Error 71 (Protocol error) dispatching to Wayland display.

**To Reproduce**
1. Open the app
2. See that nothing happens

**Expected behavior**
The app should opens.

**Technical Details (please complete the following information):**
```
 - Distribution: Ubuntu 24.10
 - Add Water version: 1.1.6

 - Browser: (Choose one: Firefox
 - Browser Package: Snap
 - Browser Version: 133
```

**Additional context**
This is a fresh installation of Ubuntu. I just installed flatpak to install the apps that are not available on Snapcraft (like Add Water).

**Attach log file if necessary**
Log from running command: `flatpak run dev.qwery.AddWater`
[Add Water flatpak run.log](https://github.com/user-attachments/files/18049564/Add.Water.flatpak.run.log)

**Comment by largestgithubuseronearth** [comment]
This very much seems like a driver issue especially with the "FINISHME" warnings from Mesa. Are you using an Intel graphics card?

It's not just an Ubuntu thing because I tested it on 24.10 a while back to fix a different bug and had no such issue.

I'll look into it some more. Thanks for reporting.

**Comment by largestgithubuseronearth** [comment]
It seems to be a driver issue from a couple of the issues that have been reported but the actual cause in this case isn't clear. For one, it was an issue with explicit sync, and for another it was due to fractional scaling, but the common motif is driver bugs for the experimental protocols.

Try running this command and post the resulting log file:
`flatpak run --env=WAYLAND_DEBUG=1 dev.qwery.AddWater &> addwater_wayland.log`

**Comment by Deewens** [comment]
Hey,

Thanks for your quick answer! I did what you asked:
[addwater_wayland.log](https://github.com/user-attachments/files/18052542/addwater_wayland.log)

Btw, I found out that this is not a problem with only your app, I just tried to install another flatpak, and I have the exact same problem. So the issue seems to be with Ubuntu (as I said, I am on a fresh install, so I haven't done anything unusual with my system). I may post a bug report on the ubuntu bug tracker.

**Comment by largestgithubuseronearth** [comment]
Took another look and I found an [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11723) that may hold some insight. The details are very similar to your case.

They determined in that case it was an Nvidia driver issue and it gets triggered when using Vulkan as your GSK renderer which is now the default in GNOME 47. 

The workaround until an Nvidia fix comes is to set the environment variable `GSK_RENDERER=gl` (OpenGL) or `GSK_RENDERER=ngl`.

Read the issue, try the workaround, and let me know how it works for you.
