### ISSUE TITLE
[BUG] Search bar narrow

### ISSUE THREAD

**Issue by PieSeek** [largestgithubuseronearth/addwater#38]
**Describe the bug**
When starting to search, the address bar is very narrow.

**To Reproduce**
1. Open Floorp
2. Click on address bar
3. See that the bar gets narrower

**Expected behavior**
The bar should stay the same width.

**Screenshots**
![add-water-bug](https://github.com/user-attachments/assets/872a2361-bfd4-4cd3-8344-40e6e0c29f74)

**Technical Details (please complete the following information):**
```
 - Distribution: OpenSUSE TW
 - Add Water 1.1.6

 - Browser: Floorp
 - Browser Package: Flatpak
 - Browser Version: v128
```

**Additional context**
Tried removing 'Add Water', then the bug dissappeared.

**Comment by largestgithubuseronearth** [comment]
Firefox had breaking changes to their UI in v133 and this was fixed in the [latest update of Firefox GNOME Theme](https://github.com/rafaelmardojai/firefox-gnome-theme/releases/tag/v133). Downside is that using FGT v133 with Firefox v132 or earlier is broken.

If Floorp has an update available, you should update. If they don't, you'll need to disable the theme until they update their base. Sorry about that.
