### ISSUE TITLE
[BUG] Librewolf Flatpak unable to select

### ISSUE THREAD

**Issue by usernaming99** [largestgithubuseronearth/addwater#47]
**Describe the bug**
When selecting 'Librewolf Flatpak' as the target and closing the 'Preferences' tab, reopening 'Preferences' shows 'Librewolf Snap' instead. Using Fedora 41.

**To Reproduce**
1. Open Add Water, click 'Preferences'
2. Click on 'Librewolf Flatpak'
3. Close 'Preferences' and then re-open it.

**Expected behavior**
Librewolf flatpak should remain selected instead of changing to Snap.

**Technical Details (please complete the following information):**
```
 - Distribution: Fedora 41
 - Add Water version: 1.2.1

 - Browser: Librewolf
 - Browser Package: Flatpak
 - Browser Version: 133.0.3-1



**Additional context**
I removed all other Firefox installs to attempt to avoid the issue but this was not successful.


**Attach log file if necessary**

[addwater_2024-12-31.log](https://github.com/user-attachments/files/18282067/addwater_2024-12-31.log)

**Comment by usernaming99** [comment]
Set to 'Automatically discover' which resolved the issue. Apologies!

**Comment by largestgithubuseronearth** [comment]
You're not the first person to bring up this issue but it always goes away after a while so I'm not sure what causes it. And the log didn't clarify what was going on because when Librewolf was selected, it reports it as successful.

Is your librewolf profile files located in `~/.librewolf/` or in `~/.var/app/io.gitlab.librewolf-community/.librewolf/`?
